### ISSUE TITLE
Dark mode text colors hard to distinguish

### ISSUE THREAD

**Issue by parmsam** [wlandau/targetsketch#12]
## Prework

* [x] I understand and agree to `targetsketch`' [code of conduct](https://github.com/wlandau/targetsketch/blob/main/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `targetsketch`' [contributing guidelines](https://github.com/wlandau/targetsketch/blob/main/CONTRIBUTING.md).
* [x] I am reasonably sure this is a genuine bug in `targetsketch` and most likely not a user error. (If you run into an error and do not know the cause, please submit a "Trouble" issue instead.)
* [x] Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Description

Please describe the bug.

Love the light mode look. On dark mode button click, text color changes to white on white for _targets.R card, black on black for Graph card, and black on black for Manifest card dataTable column names or search labels.

## Reproducible example

Be considerate of the maintainer's time and make it as easy as possible to troubleshoot any problems you identify. Read [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) and [here](https://www.tidyverse.org/help/) to learn about minimal reproducible examples. Format your code according to the [tidyverse style guide](https://style.tidyverse.org/) to make it easier for others to read.

## Expected result

What should have happened? Please be as specific as possible.

Text color should update to more easily read elements. Usually white text color on black background in dark mode.

**Comment by wlandau** [comment]
The `_targets.R` editor window is a `shinyAce` editor, the Manifest box is a `DT` output, and the Graph box is a `visNetwork` widget from `targets::tar_visnetwork()`. To make dark mode work well, each of these different components/packages would have to be aware of what `bs4Dash` is doing. So I disabled it in 3db18e83cd10d93b66f05f3d3c6dfd35c140160c.
