### ISSUE TITLE
Add button to insert code in RStudio script

### ISSUE THREAD

**Issue by parmsam** [wlandau/targetsketch#22]
## Prework

* [x] I understand and agree to `targetsketch`' [code of conduct](https://github.com/wlandau/targetsketch/blob/main/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `targetsketch`' [contributing guidelines](https://github.com/wlandau/targetsketch/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Please describe the new feature. If applicable, write a minimal example in R code or pseudo-code to show input, usage, and desired output. To help us read any code you include (optional) please try to follow the [tidyverse style guide](https://style.tidyverse.org/). The `style_text()` and `style_file()` functions from the [`styler`](https://github.com/r-lib/styler) package make it easier.

Similar to [esquisse](https://github.com/dreamRs/esquisse/blob/master/R/module-controls.R), add insert code in script link or button.

**Comment by wlandau** [comment]
Alternatively, what if `targetsketch` knew the path to `_targets.R` and could load/save/"save as", like and IDE or full word processor? I think feature-completeness in this area would help `targetsketch` act as a full workflow tool in addition to a learning tool.

**Comment by parmsam** [comment]
That's a great point! I had the same thought after I did the PR. It could be similar to the approach [{shinyuieditor}](https://rstudio.github.io/shinyuieditor/articles/quick-start.html) takes, where you can run the app to source from a new or existing location. Would you like me to make an issue for loading/saving/running the app from an existing `_targets.R` script?

**Comment by wlandau** [comment]
Sure, a new issue would be great.

Yeah, it would make sense to run the app from a saved `_targets.R` file if one exists (with default `tar_option_get("script")`). Then maybe the app could allow the user to switch to a different one.

By the way, I will be out of office from Sept 27 - Oct 14.

**Comment by parmsam** [comment]
Sounds good. I'll create that issue. Hope you have a nice vacation.

**Comment by parmsam** [comment]
Took different approached described in other issues with saving/loading. Closing issue.
