### ISSUE TITLE
Is the use of `tar_options` in the example _targets.R file intentional?

### ISSUE THREAD

**Issue by tomsing1** [wlandau/targetsketch#6]
The example pipeline presented to the user when the app is launched doesn't run, and requires the user to change
`tar_options` into `tar_option_set`, I believe. Perhaps that's intentional, e.g. to demonstrate how the app helps identify problems? Or perhaps it is an outdated reference to previous behavior changed in `targets` [in July](https://github.com/wlandau/targets/commit/0263a80864a0eae4a2e6a6e85c266d00aeeca49b)?

If it's not intentional, perhaps it's worth changing `tar_options` to `tar_option_set`?

https://github.com/wlandau/targetsketch/blob/8b495debc9589861eab84eccf8f70f99c991065d/inst/_targets.R#L3

Thanks a lot for making the `targets` set of packages available, incredibly useful!

**Comment by wlandau** [comment]
Yup, I forgot to update the app when I changed `tar_options()` to `tar_option_set()`. Thanks for catching that. Should be fixed now.
