### ISSUE TITLE
Error in tagAssert(icon, type = "i") when trying to start targetsketch on a fresh install

### ISSUE THREAD

**Issue by dewoller** [wlandau/targetsketch#7]
## Description

Just installed targetsketch on windows, using 
`> remotes::install_github("wlandau/targetsketch", INSTALL_opts="--no-multiarch")
`
I updated all the packages to the suggested version.  When I try to run targetsketch(), I get the following error:

```
> targetsketch::targetsketch()
[1] "project-diagram"
Error in tagAssert(icon, type = "i") :
  Expected an object with class 'shiny.tag'.
```

## Reproducible example

`> remotes::install_github("wlandau/targetsketch", INSTALL_opts="--no-multiarch")

## Expected result

targetsketch should run!

**Comment by wlandau** [comment]
Should be fixed now. I created `targetsketch` using `bs4Dash` 0.5.0, and `bs4Dash` 2.0.0 had a bunch of breaking changes that required workarounds.
