### ISSUE TITLE
Add button in control bs4Card to add a new target into _targets.R bs4Card

### ISSUE THREAD

**Issue by parmsam** [wlandau/targetsketch#9]
## Prework

* [x] I understand and agree to `targetsketch`' [code of conduct](https://github.com/wlandau/targetsketch/blob/main/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `targetsketch`' [contributing guidelines](https://github.com/wlandau/targetsketch/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Please describe the new feature. If applicable, write a minimal example in R code or pseudo-code to show input, usage, and desired output. To help us read any code you include (optional) please try to follow the [tidyverse style guide](https://style.tidyverse.org/). The `style_text()` and `style_file()` functions from the [`styler`](https://github.com/r-lib/styler) package make it easier.

Thanks for the package! Button in control card could open modal window where user can fill in new target info to add after the last target in `_targets.R`. User could select what arguments besides the required name and command they need. Tooltip could be display on mouse hover over argument. This would be helpful to orient new {targets} users to the available arguments for `tar_target()`. This package is a great learning tool for targets, similar to what {esquisse} provides for {ggplot2}. I can work on this if that's okay.

**Comment by wlandau** [comment]
I think this approach would work most of the time, but I also think it would make strong assumptions how the user-side code in `_targets.R` is structured.

**Comment by parmsam** [comment]
Good point. Maybe the user could still enter code into the _targets.R card for those cases. The new target button would be optional, but intended to help guide setup for most cases.
